---
version: "3.8"
services:
  freeipa:
    image: freeipa/freeipa-server:rocky-8
    hostname: ipa.test.local
    container_name: freeipa
    ports:
      - 80:80
      - 443:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp
    dns:
      - 127.0.0.1
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
    #      IPA_SERVER_HOSTNAME: ipa.test.local
    #      IPA_SERVER_IP: 192.168.0.11
      TZ: "Europe/Moscow"
    command:
      - ipa-server-install
      - --domain=test.local
      - --realm=TEST.LOCAL
      - --admin-password=12345678Qa!
      - --http-pin=12345678Qa!
      - --dirsrv-pin=12345678Qa!
      - --ds-password=12345678Qa!
      - --no-host-dns
      - --setup-dns
      - --auto-forwarders
      - --allow-zone-overlap
      - --no-dnssec-validation
      - --unattended
    cap_add:
      - SYS_TIME
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data:/data:Z
      - ./logs:/var/logs:Z
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
...

